### ISSUE TITLE
Problem when stopping upload

### ISSUE THREAD

**Issue by daganzdaanda** [kmpoppe/noteSolver#11]
Hi, I've just found this plugin, thanks for building this!

In this changeset https://www.openstreetmap.org/changeset/107319615 I had worked on 2 notes, added them to the "remember" list, added a comment to both via the JOSM notes panel. When I wanted to upload the changeset, JOSMs validator had some warnings, so I stopped the upload to fix these. 
While I was still doing that, some info popped up quickly saying something like "uploading changed notes". I don't remember doing anything to trigger this, but maybe there's a shortcut for uploading notes and I accidentally activated it? 
Then I continued with the upload of the changeset. This time, there was no pre-filled "closes notes x,y" text. 

So maybe there's an issue with interrupting an upload?

**Comment by kmpoppe** [comment]
Thank you for bringing this to my attention.
When you start the upload of the changeset, it will also automatically close the notes - Strangely enough, there shouldn't have been a Changeset Number to enter in that notes and I had thought that would stop the closing of the notes. I will have to look into this.

**Comment by kmpoppe** [comment]
Well. It seems that the Plugin got some strange CS number from some other user. I wonder how that happened. Let me assure you: The plugin works as advertised, I have done many changes using it ;-)

**Comment by kmpoppe** [comment]
Hey @daganzdaanda, I didn't see any other problems that you described, did you experience this again (Because https://www.openstreetmap.org/changeset/118108552 seems to have worked fine)?

**Comment by daganzdaanda** [comment]
Hi, I haven't used the plugin much, and that changeset was only a single change without any complications like the validator coming up with issues. I could try to recreate the problem if you want, though I'm a bit wary of using the normal openstreetmap database for testing purposes.

**Comment by daganzdaanda** [comment]
OK, I have tried to produce an error in various ways through 5 changesets with some fake data to produce validator warnings. I was not able to reproduce the issue, everything went very well! 

So I think you can close this, and I will start using the plugin more regularily to see if in "real" mapping anything comes up again. Thank you!

**Comment by kmpoppe** [comment]
Thanks @daganzdaanda !

For later reference, you can use https://master.apis.dev.openstreetmap.org/login do create yourself a dev Account (use /api instead of /login in the JOSM settings) and then you can upload everything without remorse :)

K
