### ISSUE TITLE
Add/Edit Default message

### ISSUE THREAD

**Issue by risturiz** [kmpoppe/noteSolver#19]
Hi, im using this plugin and making some tests... The option to add/edit default message should help a lot ( add additional hashtags, etc ).

Thanks.

**Comment by kmpoppe** [comment]
Hello Rafael,

thanks for your suggestion. What exactly do you mean? Like an input box before the Upload of the changeset asking for a default comment that should get added to all notes that the upload will close together with the changeset?

K

**Comment by risturiz** [comment]
Yes, like preference box? So we can add some defaults hashtags to the "close" message ( i don't know if this can be different from changeset upload and the note close upload message )... This help to save a lot of time on Notathon :-)

Thanks!

**Comment by kmpoppe** [comment]
As you might have seen, there isn't a preferences dialog as of yet. I don't remember what I was planning on doing one for, I might have to look into that again :)

**Comment by natrius** [comment]
Sounds usefull. But with variables. Because i sometimes tend to go out and resolve quite a lot of notes i stumbled already on the max-cs-comment-size as well, so i tend to shorten the links.
As said, with some predefined variables for [csnumber] or something like that, sounds good.

**Comment by angoca** [comment]
Another way could be add the following Strings in the Advanced Preferences (Expert mode), with defaults the current values.

File org.openstreetmap.josm.plugins.notesolver.NoteSolverPlugin.java

* 107: "Closes {0}"
* 114: "Closes {0}"
* 241: "Resolved with changeset {0} by noteSolver_plugin/{1}"

With keys like:

* notesolver.defaultClosesMessage
* notesolver.defaultChangesetMessage

In this way, the automatic messages can be personalized, and there is no need for a dialog.

**Comment by kmpoppe** [comment]
Closed by 4b96a6b

**Comment by kmpoppe** [comment]
This is now in the [released](https://github.com/kmpoppe/noteSolver/releases/tag/0.5.0) state, the plugin should automagically update within JOSM.

**Comment by risturiz** [comment]
For the record... Thanks again, this help a lot!

![notesolver-config](https://user-images.githubusercontent.com/12375/219880741-ab3afd14-8712-48e9-bc07-87c1bf1bfdee.png)
