### ISSUE TITLE
Popup appears in other monitor when using multiples in MacOS

### ISSUE THREAD

**Issue by angoca** [kmpoppe/noteSolver#20]
I am using MacOS Catalina, with an external monitor (+ laptop monitor). When I click on a note, the popup appears in the laptop screen, even if JOSM is on the external monitor.

**Comment by kmpoppe** [comment]
Hi angoca,

what version of the plugin are you using?

**Comment by angoca** [comment]
notesolver (0.4.2)

**Comment by angoca** [comment]
I created a Trac issue to provide all the details: https://josm.openstreetmap.de/ticket/22371#ticket

**Comment by kmpoppe** [comment]
With https://josm.openstreetmap.de/ticket/22307, a new popup for the "notes" window was added. The team will look into adding methods for adding entries into that menu.

Could you tell me whether the popup window always opens in the wrong place, no matter if you click the note on the map or in the "notes" window?

**Comment by angoca** [comment]
I attached 2 images. One when rich clicking on the note and the meny appears on the other screen. The second, when right clicking on the view, which appears in the same screen.

![Screen Shot 2022-09-15 at 12 08 30 AM](https://user-images.githubusercontent.com/294317/190319916-ccb51d5b-4050-4106-9b75-f0fa8f6270fc.png)
![Screen Shot 2022-09-15 at 12 08 46 AM](https://user-images.githubusercontent.com/294317/190319925-9ca4ac69-e30e-4698-b038-54f825fc9c0d.png)

**Comment by natrius** [comment]
Same on WIndows. Laptop left, 2 screens right from it, JOSM on the most right screen. Clicking on the note - pupup appears on the most left screen - but in the right position :D 
If i move the map around and the note is on the bottom right, the popup apperars on the most left screen (laptop) on the bottom right. If i move the note somewhere else, the popup-position will change as well  :D

But. the most left (Laptop) is marked as "Main" in Windows Settings.

**Comment by ygra** [comment]
It doesn't even need two screens. If you don't have JOSM maximized on the primary monitor the popup will appear out of place (presumably in desktop coordinates, not relative to the JOSM window). I'll look into it later and see whether I can fix it.

**Comment by ygra** [comment]
We're getting mouse coordinates relative to a component, but a context menu is shown in screen coordinates, at least when using `setLocation`. So we have to convert the desired point to screen coordinates first. I can't test right now, but the following patch might solve it:
```diff
diff --git a/notesolver/src/main/java/org/openstreetmap/josm/plugins/notesolver/NoteSolverPlugin.java b/notesolver/src/main/java/org/openstreetmap/josm/plugins/notesolver/NoteSolverPlugin.java
index 6fda01d..ec654fa 100644
--- a/notesolver/src/main/java/org/openstreetmap/josm/plugins/notesolver/NoteSolverPlugin.java
+++ b/notesolver/src/main/java/org/openstreetmap/josm/plugins/notesolver/NoteSolverPlugin.java
@@ -159,8 +159,10 @@ public class NoteSolverPlugin extends Plugin {
 				JPopupMenu contextMenu = new JPopupMenu();
 				for (JMenuItem menuItem : mainMenuEntries(menuTypes.MAIN)) 
 					contextMenu.add(menuItem);
-				Point p = MainApplication.getMainFrame().getMousePosition();
+				MainFrame frame = MainApplication.getMainFrame();
+				Point p = frame.getMousePosition();
 				if (p != null) {
+					SwingUtilities.convertPointToScreen(p, frame);
 					Component c = MainApplication.getMainFrame().getComponentAt(p);
 					JComponent jc = (JComponent)c;
 					if (c != null) {
```

**Comment by kmpoppe** [comment]
This is now in the [released](https://github.com/kmpoppe/noteSolver/releases/tag/0.5.0) state, the plugin should automagically update within JOSM.
