### ISSUE TITLE
[Feature request] button to open note in browser

### ISSUE THREAD

**Issue by joshinils** [kmpoppe/noteSolver#22]
I'd like to read the actual note on osm.org, and open relevant images taken with streetcomplete, or copy paste data taken on location from the note from there

**Comment by ygra** [comment]
This does already exist in the Notes panel:
![image](https://user-images.githubusercontent.com/1692688/211190666-36e8badc-e930-4f57-9176-014589a67d38.png)

**Comment by joshinils** [comment]
would help if I ever used that beforehand :eyes:. well ok then.

though it is a bit unwieldy to select a note icon, then select the note entry in the list, then right click the selected note and then open in browser.

and i have to select "remember note" anyway in the popup (on the other monitor, even on ubuntu, ref: #20), so placing the same open in browser seems valid to me here

**Comment by ygra** [comment]
Ah, so this is about the context menu. I initially thought this to be about the confirmation dialog prior to uploading.

**Comment by kmpoppe** [comment]
I have no quarries with putting an "open in Browser" link into the menu(s) for the note so that you don't have to move between the additional window and the menu.

**Comment by kmpoppe** [comment]
This is now in the [released](https://github.com/kmpoppe/noteSolver/releases/tag/0.5.0) state, the plugin should automagically update within JOSM.
