### ISSUE TITLE
Would it be worthwhile to also include closed:note on the changeset?

### ISSUE THREAD

**Issue by ygra** [kmpoppe/noteSolver#23]
https://wiki.openstreetmap.org/wiki/Key:closed:note

iD does this, which is perhaps a more machine-readable marker which notes have been closed with a given changeset.

**Comment by kmpoppe** [comment]
Interesting idea. When the wiki is back up, I'll be reading up on that.

Thanks for the tip!

**Comment by ygra** [comment]
Here's a screenshot, as that page has been sitting open for days here :)
![image](https://user-images.githubusercontent.com/1692688/214797360-abcf9c9b-976a-4dec-9ffd-8c0027d9691f.png)

**Comment by kmpoppe** [comment]
Do you have a changeset handy that has it? Because OsmCha won't let me search for that kind of metadata 🙄

**Comment by ygra** [comment]
https://www.openstreetmap.org/changeset/121857995

**Comment by kmpoppe** [comment]
This is now in the [released](https://github.com/kmpoppe/noteSolver/releases/tag/0.5.0) state, the plugin should automagically update within JOSM.
