### ISSUE TITLE
Empty closed:note key in changeset tags

### ISSUE THREAD

**Issue by ygra** [kmpoppe/noteSolver#25]
When _not_ closing a note, this sometimes happens: https://www.openstreetmap.org/changeset/132703728

JOSM complains about it, and I decided to look whether it would actually appear in the changeset tags. Yes, it does, and it's empty.

**Comment by kmpoppe** [comment]
... and I always thought the API would prevent empty keys AND I thought I had prevented adding the field when the value was empty.

I seem to have been mistaken on both accounts 🤦‍♂️
