### ISSUE TITLE
Note not automatically resolved

### ISSUE THREAD

**Issue by SlidingHorn** [kmpoppe/noteSolver#9]
Hey there! I was the one who submitted the error report for #8 - Thanks for having that fixed so quickly.

I might have come across another issue:

I selected a [note](https://www.openstreetmap.org/note/2716154), clicked "Remember" and made my changes. When I uploaded the [changeset](https://www.openstreetmap.org/changeset/106988756), it did ask if I wanted to resolve, and I clicked yes. It appears as though the changeset properly referenced the note, but for some reason, the note itself was not auto-resolved.

Any idea what might have happened here?

Thanks again!

**Comment by kmpoppe** [comment]
Morning!

That's quite strange. If the plug-in didn't throw an exception it seems to not even have tried to close the note.

I will have to check that in the Dev map.

Thanks for reporting this!

**Comment by kmpoppe** [comment]
Hi!

I couldn't reproduce this error in the DEV system, please try again with any other note the next time. If the problem persists, I will have to see how to reproduce this error.

Kai

**Comment by SlidingHorn** [comment]
I'll close this for now as being a one-time hiccup. If it happens again, I'll come back with more information and reference this issue.

Have a great weekend!
